### ISSUE TITLE
Proposal to track Microsoft

### ISSUE THREAD

**Issue by bobh0303** [simoncozens/opentypespec-py#2]
As best as I can calculate, at this point there are 611 Language tags in this package, 632 in the current Working Draft for the ISO/IEC 14496-22, and 635 in the Microsoft OT spec. 

Is there a reason this repo tracks the tag registry of the ISO/IEC spec rather than that of the Microsoft OpenType spec? 

It seems like ISO/IEC _eventually_ adopts any script, language or feature tags registered by Microsoft, but it takes many months for changes published in the Microsoft specification to bubble through to a release of the ISO/IEC. In the mean time users of fontbakery are getting FAILs for including support for languages that have not yet bubbled through to ISO/IEC. 

If we must track the ISO/IEC spec, could we track Working Drafts as well as releases?

**Comment by bobh0303** [comment]
Any thoughts on this idea?

**Comment by simoncozens** [comment]
The ideal would be if Microsoft actually released their OT registries in a machine-readable format, instead of requiring me to go and screen-scrape it every minor release. :-/

**Comment by simoncozens** [comment]
I've finally updated this to OpenType 1.9.0. Sorry about the delay.
